groups:
  - name: master
    jobs:
      <% for ruby_version in RUBIES[:mri] %>
      - "ruby-<%= ruby_version %>-system"
      - "ruby-<%= ruby_version %>-vendored"
      - "ruby-<%= ruby_version %>-valgrind"
      <% end %>
      - "ruby-vanilla-system"
      <% for ruby_version in RUBIES[:mri].last(1) %>
      - "ruby-libxmlruby-system"
      - "ruby-libxmlruby-vendored"
      - "ruby-libxmlruby-valgrind"
      <% end %>
      <% for jruby_version in RUBIES[:jruby] %>
      - "jruby-<%= jruby_version %>"
      <% end %>
      <% for rbx_version in RUBIES[:rbx] %>
      - "rbx-<%= rbx_version %>-system"
      - "rbx-<%= rbx_version %>-vendored"
      <% end %>
      <% RUBIES[:windows].first(1).each do |ruby_version| %>
      - "win-ruby-<%= ruby_version %>-devkit"
      <% end %>
      - build-success


  - name: PRs
    jobs:
      - pr-pending
      - ruby-<%= RUBIES[:mri].first %>-system-pr
      - ruby-<%= RUBIES[:mri].first %>-vendored-pr
      - ruby-<%= RUBIES[:mri].first %>-valgrind-pr
      - ruby-<%= RUBIES[:mri].last %>-system-pr
      - ruby-<%= RUBIES[:mri].last %>-vendored-pr
      - ruby-<%= RUBIES[:mri].last %>-valgrind-pr
      - ruby-vanilla-system-pr
      - jruby-<%= RUBIES[:jruby].last %>-pr
      - rbx-<%= RUBIES[:rbx].last %>-pr
      - pr-success

  - name: allow-failure
    jobs:
      <% RUBIES[:windows].last(2).each do |ruby_version| %>
      - "win-ruby-<%= ruby_version %>-devkit"
      <% end %>


resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
- name: irc-notification
  type: docker-image
  source:
    repository: flavorjones/irc-notification-resource

resources:
  - name: ci
    type: git
    source:
      uri: https://github.com/sparklemotion/nokogiri/
      branch: master
      disable_ci_skip: true # always get the latest pipeline configuration
  - name: nokogiri
    type: git
    source:
      uri: https://github.com/sparklemotion/nokogiri/
      branch: master
      ignore_paths:
        - concourse/**
  - name: nokogiri-pr
    type: pull-request
    source:
      repo: sparklemotion/nokogiri
      access_token: {{github-repo-status-access-token}}
      ignore_paths:
        - concourse/**
  - name: nokogiri-irc
    type: irc-notification
    source:
      server: chat.freenode.net
      port: 7070
      channel: "#nokogiri"
      user: {{nokobot-irc-username}}
      password: {{nokobot-irc-password}}

anchors:
  notify_failure_to_irc: &notify_failure_to_irc
    put: nokogiri-irc
    params: {message: "($BUILD_PIPELINE_NAME/$BUILD_JOB_NAME) The build failed ($BUILD_URL)"}
  notify_failure_to_pr: &notify_failure_to_pr
    put: nokogiri-pr
    params: {path: nokogiri-pr, status: failure}

jobs:
  #
  #  master
  #
  <% for ruby_version in RUBIES[:mri] %>
  - name: ruby-<%= ruby_version %>-system
    public: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri
          params:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc

  - name: ruby-<%= ruby_version %>-vendored
    public: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["ruby-<%= ruby_version %>-system"]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc

  - name: ruby-<%= ruby_version %>-valgrind
    public: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["ruby-<%= ruby_version %>-vendored"]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri
          params:
            TEST_WITH_VALGRIND: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc
  <% end %>

% ruby_version = RUBIES[:mri].last
  - name: ruby-vanilla-system
    public: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["ruby-<%= ruby_version %>-system"]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu, tag: xenial}
          inputs:
            - name: ci
            - name: nokogiri
          params:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
            TEST_WITH_APT_REPO_RUBY: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc

  - name: ruby-libxmlruby-system
    public: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri
          params:
            BUNDLE_GEMFILE: "Gemfile-libxml-ruby"
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc

  - name: ruby-libxmlruby-vendored
    public: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["ruby-libxmlruby-system"]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri
          params:
            BUNDLE_GEMFILE: "Gemfile-libxml-ruby"
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc

  - name: ruby-libxmlruby-valgrind
    public: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["ruby-libxmlruby-vendored"]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri
          params:
            BUNDLE_GEMFILE: "Gemfile-libxml-ruby"
            TEST_WITH_VALGRIND: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc

  <% for jruby_version in RUBIES[:jruby] %>
  - name: jruby-<%= jruby_version %>
    public: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
      - task: rake-test
        attempts: 3
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: jruby, tag: "<%= jruby_version %>-jdk"}
          inputs:
            - name: ci
            - name: nokogiri
          params:
            JAVA_OPTS: "-Dfile.encoding=UTF8" # https://github.com/docker-library/openjdk/issues/32
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc
  <% end %>

  <% for rbx_version in RUBIES[:rbx] %>
  - name: rbx-<%= rbx_version %>-system
    public: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
      - task: rake-test
        config:
          image_resource:
            type: docker-image
            source: {repository: rubinius/docker, tag: "<%= rbx_version %>"}
          platform: linux
          inputs:
            - name: ci
            - name: nokogiri
          params:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
            TMPDIR: /scratch
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc

  - name: rbx-<%= rbx_version %>-vendored
    public: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["rbx-<%= rbx_version %>-system"]
      - task: rake-test
        config:
          image_resource:
            type: docker-image
            source: {repository: rubinius/docker, tag: "<%= rbx_version %>"}
          platform: linux
          inputs:
            - name: ci
            - name: nokogiri
          params:
            TMPDIR: /scratch
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc
  <% end %>

  <% for ruby_version in RUBIES[:windows] %>
  - name: win-ruby-<%= ruby_version %>-devkit
    public: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
      - task: rake-test
        config:
          platform: windows
          inputs:
            - name: ci
            - name: nokogiri
          params:
            WIN_RUBY_VERSION: "<%= ruby_version %>"
          run:
            path: powershell
            args: ["-File", "ci/concourse/tasks/rake-test/run.ps1"]
  <% end %>

  - name: build-success
    public: true
    disable_manual_trigger: true
    plan:
      - get: nokogiri
        trigger: true
        version: every
        passed:
          <% for ruby_version in RUBIES[:mri] %>
          - "ruby-<%= ruby_version %>-valgrind"
          <% end %>
          <% for ruby_version in RUBIES[:mri].last(1) %>
          - "ruby-libxmlruby-valgrind"
          <% end %>
          <% for jruby_version in RUBIES[:jruby] %>
          - "jruby-<%= jruby_version %>"
          <% end %>
          <% for rbx_version in RUBIES[:rbx] %>
          - "rbx-<%= rbx_version %>-vendored"
          <% end %>
          <% RUBIES[:windows].first(1).each do |ruby_version| %>
          - "win-ruby-<%= ruby_version %>-devkit"
          <% end %>
      - put: nokogiri-irc
        params: {message: "($BUILD_PIPELINE_NAME/$BUILD_JOB_NAME) The build passed ($BUILD_URL)"}

  #
  #  PRs
  #
  - name: pr-pending
    public: true
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
      - put: nokogiri-pr
        params: {path: nokogiri-pr, status: pending}

  <% [RUBIES[:mri].first, RUBIES[:mri].last].each do |ruby_version| %>
  - name: ruby-<%= ruby_version %>-system-pr
    public: true
    max_in_flight: 1
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: [pr-pending]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri-pr
              path: nokogiri
          params:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: { aggregate: [*notify_failure_to_irc, *notify_failure_to_pr] }

  - name: ruby-<%= ruby_version %>-vendored-pr
    public: true
    max_in_flight: 1
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: [pr-pending]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri-pr
              path: nokogiri
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: { aggregate: [*notify_failure_to_irc, *notify_failure_to_pr] }

  - name: ruby-<%= ruby_version %>-valgrind-pr
    public: true
    max_in_flight: 1
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: [pr-pending]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri-pr
              path: nokogiri
          params:
            TEST_WITH_VALGRIND: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: { aggregate: [*notify_failure_to_irc, *notify_failure_to_pr] }
  <% end %>

% ruby_version = RUBIES[:mri].last
  - name: ruby-vanilla-system-pr
    public: true
    max_in_flight: 1
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: ["ruby-<%= ruby_version %>-system-pr"]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu, tag: xenial}
          inputs:
            - name: ci
            - name: nokogiri-pr
              path: nokogiri
          params:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
            TEST_WITH_APT_REPO_RUBY: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: { aggregate: [*notify_failure_to_irc, *notify_failure_to_pr] }

% jruby_version = RUBIES[:jruby].last
  - name: jruby-<%= jruby_version %>-pr
    public: true
    max_in_flight: 1
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: [pr-pending]
      - task: rake-test
        attempts: 3
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: jruby, tag: "<%= jruby_version %>-jdk"}
          inputs:
            - name: ci
            - name: nokogiri-pr
              path: nokogiri
          params:
            JAVA_OPTS: "-Dfile.encoding=UTF8" # https://github.com/docker-library/openjdk/issues/32
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: { aggregate: [*notify_failure_to_irc, *notify_failure_to_pr] }

% rbx_version = RUBIES[:rbx].last
  - name: rbx-<%= rbx_version %>-pr
    public: true
    max_in_flight: 1
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: [pr-pending]
      - task: rake-test
        config:
          image_resource:
            type: docker-image
            source: {repository: rubinius/docker, tag: "<%= rbx_version %>"}
          platform: linux
          inputs:
            - name: ci
            - name: nokogiri-pr
              path: nokogiri
          params:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
            TMPDIR: /scratch
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: { aggregate: [*notify_failure_to_irc, *notify_failure_to_pr] }

  - name: pr-success
    public: true
    disable_manual_trigger: true
    plan:
      - get: nokogiri-pr
        trigger: true
        version: every
        passed:
          - ruby-<%= RUBIES[:mri].first %>-system-pr
          - ruby-<%= RUBIES[:mri].first %>-vendored-pr
          - ruby-<%= RUBIES[:mri].first %>-valgrind-pr
          - ruby-<%= RUBIES[:mri].last %>-system-pr
          - ruby-<%= RUBIES[:mri].last %>-vendored-pr
          - ruby-<%= RUBIES[:mri].last %>-valgrind-pr
          - ruby-vanilla-system-pr
          - jruby-<%= RUBIES[:jruby].last %>-pr
          - rbx-<%= RUBIES[:rbx].last %>-pr
      - put: nokogiri-pr
        params: {path: nokogiri-pr, status: success}
      - put: nokogiri-irc
        params: {message: "($BUILD_PIPELINE_NAME/$BUILD_JOB_NAME) The build passed ($BUILD_URL)"}
